dataset_config = {
    'trento': {
        'dataset_dir': '../DATASET/trento',
        'num_class': 6,
        'hsi_n_feature': 63,
        'lidar_n_feature': 1,
        'concate_pixel': (3, 3, 3, 3),
        'class_labels' : {
            -1: 'Undefined',
            1: 'Apples',
            2: 'Buildings',
            3: 'Ground',
            4: 'Woods',
            5: 'Vineyard',
            6: 'Road',
        }
    },
    'houston13': {
        'dataset_dir': '../DATASET/houston13',
        'num_class': 15,
        'hsi_n_feature': 144,
        'lidar_n_feature': 21,
        'concate_pixel': (3, 3, 3, 3),
        'class_labels': {
            0: 'Unclassified',
            1: 'Healthy grass',
            2: 'Stressed grass',
            3: 'Synthetic grass',
            4: 'Trees',
            5: 'Soil',
            6: 'Water',
            7: 'Residential',
            8: 'Commercial',
            9: 'Road',
            10: 'Highway',
            11: 'Railway',
            12: 'Parking Lot 1',
            13: 'Parking Lot 2',
            14: 'Tennis Court',
            15: 'Running Track'
        },
    },
    'muufl': {
        'dataset_dir': '../DATASET/muufl',
        'num_class': 11,
        'hsi_n_feature': 64,
        'lidar_n_feature': 2,
        'concate_pixel': (3, 3, 3, 3),
        'class_labels': {
            -1: 'Unlabeled',
            1: 'Trees',
            2: 'Mostly Grass',
            3: 'Mixed Ground',
            4: 'Dirt and Sand',
            5: 'Road',
            6: 'Water',
            7: 'Buildings',
            8: 'Shadow of Buildings',
            9: 'Sidewalk',
            10: 'Yellow Curb',
            11: 'Cloth Panels'
        },
    },
    'augsburg': {
        'dataset_dir': '../DATASET/augsburg',
        'num_class': 11,
        'hsi_n_feature': 180,
        'lidar_n_feature': 1,
        'concate_pixel': (3, 3, 3, 3),
        'class_labels': {
            0: "Unclassified",
            1: "Forest",
            2: "Residential Area",
            3: "Industrial Area",
            4: "Low Plants",
            5: "Allotment",
            6: "Commercial Area",
            7: "Water"
        },
    },
}

custom_colors = [
    [0, 0, 205],
    [0, 8, 255],
    [0, 77, 255],
    [0, 145, 255],
    [0, 212, 255],
    [41, 255, 206],
    [96, 255, 151],
    [151, 255, 96],
    [206, 255, 41],
    [255, 230, 0],
    [255, 167, 0],
    [255, 104, 0],
    [255, 41, 0],
    [205, 0, 0],
    [128, 0, 0]
]